name: Android CI

on:
  push:
    branches: [ main, cursor/** ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install deps
        working-directory: backend
        run: npm ci || npm install
      - name: Typecheck
        working-directory: backend
        run: npm run build
      - name: Lint
        working-directory: backend
        run: npm run lint
      - name: Unit tests
        working-directory: backend
        run: npm test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Gradle Wrapper (android project)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
          build-root-directory: android
          arguments: wrapper

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew --no-daemon assembleDebug

      - name: List APK outputs
        working-directory: android
        run: |
          ls -R app/build/outputs || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: |
            android/app/build/outputs/apk/**/*.apk
          if-no-files-found: warn

      - name: Run unit tests
        working-directory: android
        run: ./gradlew --no-daemon testDebugUnitTest

  connected-tests:
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
    needs: build
    runs-on: macos-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Gradle Wrapper (android project)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
          build-root-directory: android
          arguments: wrapper

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Run connected tests (API 30)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel_5
          script: |
            cd android
            ./gradlew --no-daemon assembleDebug
            ./gradlew --no-daemon connectedDebugAndroidTest

